### ISSUE TITLE
I just installed proxmox 6.1 via pxe with this script.

### ISSUE THREAD

**Issue by kroko23** [morph027/pve-iso-2-pxe#12]
Hi,
I want to let you know that this script works on proxmox 6.1 too. I just installed using your script to  convert iso.
Thanks

I used lpxeboot.0 with the following config:

 menu label ^7) Proxmox 6.1
   LINUX http://server/proxmox61/linux26
   append initrd=http://server/proxmox61/initrd.iso.img vga=791 video=vesafb:ywrap,mtrr ramdisk_size=16777216 rw

**Comment by morph027** [comment]
Thanks for your hint!

**Comment by PinkPantherchen** [comment]
Hi, 
i used it to day for installing Proxmox 6.2.1 over pxe script works really fine .. thanks for this, on my "old" HP Prolian ML115 G5 is just had to use the following PXE Entry:

label proxmox-install-hp
         menu label Proxmox 6.2.1
         kernel proxmox/linux26
         append initrd=proxmox/initrd.iso.img vga=791 video=vesafb:ywrap,mtrr ramdisk_size=166777216 linux ext4 maxroot=4 swapsize=4 splash=verbose

because with the other entry you mentioned i got a kernel-panic ..
