### ISSUE TITLE
Booting Proxmox over UEFI with FTP

### ISSUE THREAD

**Issue by boospy** [morph027/pve-iso-2-pxe#13]
Hello, 

booting ober tftp works really fine, but needs a lot of time. So HTTP/ftp would be better. But how does this work on UEFI  PXE? With tftp it works like this:

```
menuentry 'Proxmox 6.2' --id proxmox62 {
  linuxefi /proxmox62/linux26 vga=791 video=vesafb:ywrap,mtrr ramdisk_size=2000000 linux ext4 maxroot=60 swapsize=16 splash=verbose
  initrdefi /proxmox62/initrd.iso.img
}
```
But with ftp for example it means "you must boot the kernel first". So i think my syntax is not correct. 

```
menuentry 'Proxmox 6.2 Faster' --id proxmox62-ftp {
  linuxefi url=ftp://data.osit.cc/pxe-iso/proxmox/linux26 vga=791 video=vesafb:ywrap,mtrr ramdisk_size=2000000 linux ext4 maxroot=60 swapsize=16 splash=verbose
  initrdefi url=ftp://data.osit.cc/pxe-iso/proxmox/initrd.iso.img
}
```

**Comment by morph027** [comment]
Hm, not sure, i'm using ipxe only with UEFI which works like described in the README.

**Comment by boospy** [comment]
Ok, so the best way is to test this with HTTP.
