### ISSUE TITLE
Unable to boot  uefi ipxe install

### ISSUE THREAD

**Issue by assid2** [morph027/pve-iso-2-pxe#15]
I tried the following, but getting a kernel panic not syncing VFS unable to mount root fs on unknown block 0,0

:proxmox-install
echo Starting Proxmox Install 6.2.1 
set base-url http://172.16.120.52/install/iso/extractedinstall/proxmox-ve_6.2-1
kernel ${base-url}/linux26
initrd ${base-url}/initrd.iso.img
#imgargs linux26 initrd=initrd.iso.img vga=791 video=vesafb:ywrap,mtrr ramdisk_size=166777216 linux ext4 maxroot=4 swapsize=4 splash=verbose || shell
boot || shell
goto start

**Comment by morph027** [comment]
Why did you comment the args?

**Comment by fulafisken** [comment]
I had this same message. I modified the script to not pipe any errors to dev/null, and then i found out my Arch installation did not have cpio:

Added iso, creating and compressing the new initrd...
pve-script.sh: line 59: cpio: command not found

So after installing that, and running the script again, then it works! :) 
pacman -S cpio

**Comment by Exellent1988** [comment]
I didnt get it to work with different PVE Versions: this is my latest test:

:proxmox-64-efi
set base-url http://XXX.XXX.XXX.XXX/tools/proxmox
kernel  ${base-url}/6.4/pxeboot/linux26
initrd  ${base-url}/6.4/pxeboot/initrd.iso.img
imgargs linux26 initrd=initrd.iso.img vga=791 video=vesafb:ywrap,mtrr ramdisk_size=166777216 linux ext4 maxroot=4 swapsize=4 splash=verbose 
boot || shell
goto start

I still get the kernel panic, but cant see any errors in the script. 🤷🏽

**Comment by Exellent1988** [comment]
UPDATE: I got the 6.4 working like this:
:proxmox-6
set base-url http://SERVERIP/tools/proxmox
initrd ${base-url}/6.4/pxeboot/initrd.iso.img
kernel ${base-url}/6.4/pxeboot/linux26 iso vga=791 video=vesafb:ywrap,mtrr ramdisk_size=16777216 rw quiet splash=silent initrd=initrd.iso.img
boot || goto failed
goto start
