### ISSUE TITLE
Lift root requirement

### ISSUE THREAD

**Issue by aadnehovda** [morph027/pve-iso-2-pxe#17]
I had a stab at a version which does not require root access, and actually not even mounting or repackaging at all. Using isoinfo we can directly extract the kernel and the initrd. As it turns out (via https://unix.stackexchange.com/questions/243657) you can simply append another gzipped cpio archive to the original initrd.img and the kernel will happily read both archives and merge them together into the initramfs.

```bash
#!/bin/env bash

isoinfo -i proxmox.iso -R -x /boot/linux26 > linux26
isoinfo -i proxmox.iso -R -x /boot/initrd.img > initrd.img
echo 'proxmox.iso' | cpio -H newc -o | gzip --best >> initrd.img
```

**Comment by morph027** [comment]
Thank you, this looks really good. Will implement this!

**Comment by aadnehovda** [comment]
The ISO is only slightly compressible even with `gzip --best`, only ~2%, so that step can probably be skipped too. (Taken from the SO link that the kernel accepts parts of the initrd.img that are either compressed or not. Not tested.)
