### ISSUE TITLE
isoinfo is not found

### ISSUE THREAD

**Issue by Darthmogra** [morph027/pve-iso-2-pxe#19]
/pve-iso-2-pxe.sh: sor: 42: isoinfo: not found

my command: bash pve-iso-2-pxe.sh /mnt/data/isos/proxmox-ve_6.4-1.iso

**Comment by Darthmogra** [comment]
I found the problem
i run this script on a raspberry pi and missing this "apt-get install genisoimage"

**Comment by morph027** [comment]
Will add it to the README, thanks for the hint!
