### ISSUE TITLE
Please port it for Proxmox 5.0

### ISSUE THREAD

**Issue by boospy** [morph027/pve-iso-2-pxe#2]
Hallo, 

since 4.4. The convertprocess does not work correctly... i think. Because on boot with PXE with the files there is an kernelpanic. With 5.0 the same problem. 

Can you debug the process to change the script for PVE5?

Bootlines:
```
LABEL Proxmox-50
    MENU LABEL Proxmox 5.0 PVE Environment
    TEXT HELP
         Installiert einen Virtualisierungshost mit Proxmox 5.0
    ENDTEXT
    LINUX proxmox50/linux26
    APPEND root=/dev/ram0 vga=791 ramdisk_size=777216 linux ext4 maxroot=25 swapsize=4 splash=verbose
    INITRD proxmox50/initrd.iso.img
```

Thanks a lot

**Comment by morph027** [comment]
Hm...tried with fresh ISO, works for me. Can you take a photo of the kernel panic please?

**Comment by boospy** [comment]
![screenshot_20170711_193022](https://user-images.githubusercontent.com/7432752/28081478-b0cbc4c8-666f-11e7-887f-94149ad48d0a.png)
This is virtual in PVE. Same is in Virtualbox. I tested this always in this virtual maschines. PVE 4.2 is working fine.

**Comment by morph027** [comment]
Hm....Ok, just firing up a VirtualBox VM inside PVE to test...

My md5sums are:

```
228dd53e34c3d224e3505554696c3b9d  initrd.iso.img
56b2e4f54dd0133c7e6d4d619b9f5f1e  linux26
```

**Comment by morph027** [comment]
Ok...works here in vbox too ...

![Screenshot_2017-07-11 20-56-11](https://user-images.githubusercontent.com/600106/28085250-65423dd2-667b-11e7-8ae8-d3eb58d5dc8f.png)

I see a QEMU DVD Drive in your kernel output...can you try to remove it? Probably the installer thinks there's an CD inside and tries to load instead of the packaged one (will have a look at the installer script to doublecheck)

**Comment by boospy** [comment]
Same thing without DVDdrive. Really strange. I have also an other Checksum on initrd.iso.img. Ok, i download everything again. And test again.

**Comment by morph027** [comment]
Can upload my files tomorrow...

**Comment by morph027** [comment]
https://play.minio.io:9000/morph027/initrd.iso.img?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20170712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170712T093210Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=90d8f045f96dc1b7eee8810ff6e4262b06faa2039b7b01b07dcf650ea3a51616

**Comment by morph027** [comment]
https://play.minio.io:9000/morph027/linux26?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20170712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170712T093402Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=6a5995450d2950ca44c44f05e9636d82830909456886c7f22df99c5b6e706f47

**Comment by boospy** [comment]
Ok solved :sunglasses: 

What was the problem? ... on all us servers we use unixacl's. On most folders the executables will discarded on creating files. And a other ACL's. I don't know what, but since 4.3 the initrd.iso.img was no working anymore. Easy solution: Remove all ACL's from buildfolder.
