### ISSUE TITLE
Failed to extract initrd using latest commit.

### ISSUE THREAD

**Issue by aurrak** [morph027/pve-iso-2-pxe#20]
The latest commit `176d4db` (the one that added Proxmox 7.0 support) seems to break backwards compatibility on proxmox-ve_6.4-1.iso.

```
Using proxmox-ve_6.4-1.iso...
extracting kernel...
extracting initrd...
gzip: /tmp/initrd.img: unknown suffix -- ignored
gzip: initrd.gz: No such file or directory
```

Reverting back to commit `f36b384` seems to work.

**Comment by morph027** [comment]
Thanks for the info. Should have tried ;)

Latest commit works for me now.
