### ISSUE TITLE
kernel panic on PXE boot

### ISSUE THREAD

**Issue by trollqaa** [morph027/pve-iso-2-pxe#21]
Hello.
After creating the files and attempting to boot via PXE, the kernel panics.
Tried both Proxmox VE 6.4 and Proxmox VE 7.0

BIOS legacy (not UEFI), platform Supermicro X8DTU with X5670 

PXE configuration in my python script:
```
:proxmox_6
echo Proxmox VE 6
echo Load kernel...
kernel {{ request.url_root }}images/proxmox/6/linux26
echo Load initrd...
initrd {{ request.url_root }}images/proxmox/6/initrd
imgargs linux26 vga=791 ramdisk_size=16777216 quiet splash=verbose proxdebug
echo Boot
boot || goto special
goto special

:proxmox_7
echo Proxmox VE 7
echo Load kernel...
kernel {{ request.url_root }}images/proxmox/7/linux26
echo Load initrd...
initrd {{ request.url_root }}images/proxmox/7/initrd
imgargs linux26 vga=791 ramdisk_size=16777216 quiet splash=verbose proxdebug
echo Boot
boot || goto special
goto special
```

In the attachment there is a screenshot of the problem:
![2021-07-13_19-02](https://user-images.githubusercontent.com/7746583/125486544-d3f2ac5d-9c7e-482d-99e3-9d2500fd3167.png)

**Comment by morph027** [comment]
Hm, i was able to boot via BIOS in a PVE VM. I do not have any BIOS enabled hardware to test further. You could try to [chainload](https://ipxe.org/howto/dhcpd#pxe_chainloading) IPXE and see if it works this way.

**Comment by platinum55** [comment]
got the same problem with BIOS and EFI boot

**Comment by trollqaa** [comment]
> got the same problem with BIOS and EFI boot

read again...
LEGACY BIOS

**Comment by platinum55** [comment]
I tried both BIOS Legacy _AND_ UEFI mode... both give the kernel panic error

**Comment by trollqaa** [comment]
> I tried both BIOS Legacy _AND_ UEFI mode... both give the kernel panic error

its bad :(

**Comment by Exellent1988** [comment]
Me to; im  always getting the 
`VFS: Cannot open root device "(null)" or unknown-block(0,0).....`  for PVE 7.0.1 ( UEFI & LEGACY BIOS)
@morph027 could you post your working  ipxe entry? The one in the readme isnt working, at least at my end.

for the 6.4 this one is working fine for me in LEGACY AND UEFI MODE (both iPXE)

https://github.com/morph027/pve-iso-2-pxe/issues/15#issuecomment-832748543

**Comment by Exellent1988** [comment]
I digged in a little deeper, and it seems like that the initrd.img doesn't get decompressed, because its not a compressed file. So the $decompress value is not set at all.

**Comment by morph027** [comment]
Its not compressed anymore, right, but should not matter.

**Comment by Exellent1988** [comment]
what i dont understand, why is the filesize of the initrd (inc. iso) not bigger that the iso itself, shouldnt it be the initrd.img + iso?

**Comment by morph027** [comment]
Jip, it should. Mine is ~1GB in size.

**Comment by morph027** [comment]
```
# ls -larth
-r--r--r-- 1 root   root     12M May 24 08:29 linux26
-rw-r--r-- 1 root   root   1005M May 24 09:21 initrd
```

**Comment by Exellent1988** [comment]
well, than the not compressed image is the problem: check your sourcecode, if the mimetype is not found, then the $decompress value will not be set and the initrd.img will be in /tmp/initrd.img. And the iso will pe appendet, to ./initrd, but this is an empty file ATM ( if no mimetype is found).
so all your scipt does is more or less renaming the .iso to initrd :)
for compare, the initrd.img is mine done manually, and initrd is done by the script:
`
-r--r--r-- 1 root root 1097978170 Jul 26 13:12 initrd.img
`
`
-rw-r--r-- 1 root root 1064886784 Jul 23 15:10 initrd
`
there you see the size difference.
I still dont get it to properly boot, now im stuck on finding the iso ...

**Comment by Exellent1988** [comment]
bzw thats the size of the iso itself
`-rw-r--r-- 1 root root 1064886272 Jul 23 09:58 proxmox-ve_7.0-1.iso
`

**Comment by morph027** [comment]
Thanks for debugging. Will have a look later!

**Comment by Exellent1988** [comment]
I've testet the 7.0.1 iso with the 6.4 initrd, at least the kernel finds the iso but it runs into other problems:
![PXL_20210726_134819763](https://user-images.githubusercontent.com/5496003/126999988-d0cbc7ee-8128-4f5a-a040-e991fdf92ccb.jpg)
Any ideas what i clould try, or what else i could debugg?

**Comment by morph027** [comment]
Can you try the latest commit please?

**Comment by Exellent1988** [comment]
okay at least that works :)
`Using proxmox-ve_7.0-1_new.iso...`
`extracting kernel...`
`extracting initrd...`
`unable to detect initrd compression method, exiting`

But i still havent found a way to boot 7.0 :|

**Comment by morph027** [comment]
What does `which file` says on your system?

**Comment by Exellent1988** [comment]
`file /tmp/initrd.img
/tmp/initrd.img: data
`
I even tryed to binwak the file, but i can't get how the builded the initrd?!

**Comment by morph027** [comment]
and `file --mime-type --brief /tmp/initrd.img` ?

**Comment by Exellent1988** [comment]
`file --mime-type --brief /tmp/initrd.img`
`application/octet-stream
`

**Comment by morph027** [comment]
Ah, well, that's the reason why it fails to decompress ;)

Which OS are you running?

**Comment by Exellent1988** [comment]
do you have another iso than me? i downloaded mine now a few times, from :
https://www.proxmox.com/en/downloads/item/proxmox-ve-7-0-iso-installer ( 7.0-1)

Here my sysinfos:
Linux pxeinstall 3.16.0-11-686-pae #1 SMP Debian 3.16.84-1 (2020-06-09) i686 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

**Comment by morph027** [comment]
Ah, looks like the `file` command in Debian 8 is too old to recognize the new formats. Can you run docker?

**Comment by Exellent1988** [comment]
Na, I will update the system :) and report back it that helped, but i allready tryed the compressiondetection on my wsl, and it looks like it worked.

**Comment by trollqaa** [comment]
@morph027 
```
[root@node2 prox]# bash pve-iso-2-pxe.sh prox.iso

#########################################################################################################
# Create PXE bootable Proxmox image including ISO                                                       #
#                                                                                                       #
# Author: mrballcb @ Proxmox Forum (06-12-2012)                                                         #
# Thread: http://forum.proxmox.com/threads/8484-Proxmox-installation-via-PXE-solution?p=55985#post55985 #
# Modified: morph027 @ Proxmox Forum (23-02-2015) to work with 3.4                                      #
#########################################################################################################

Using prox.iso...
extracting kernel...
extracting initrd...
unable to detect initrd compression method, exiting
```
OS info:
```
[root@node2 prox]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

**Comment by morph027** [comment]
Okay, looks like the same, your `file` command is too old to recognize the data types. Can you upgrade or run docker on your system?

**Comment by trollqaa** [comment]
On ubuntu 20.04 this script working (but i dont check boot from this pxe files)
I'll check it a little later and write it to the issue

**Comment by Exellent1988** [comment]
okay i got i now working in UEFI and legacy mode. my changes have been allready added in this Pull request : https://github.com/morph027/pve-iso-2-pxe/pull/23
:)

**Comment by fansari** [comment]
I also had this problem with  proxmox-ve_7.0-1.iso about "unable to detect initd compression method" but this was easy to fix.
Here I had to replace "zstd" with "x-zstd" and then it worked:
```
case "${mimetype##*/}" in
  "x-zstd")
    decompress="zstd -d /tmp/initrd.img -o initrd"
    ;;
```

**Comment by fansari** [comment]
But unfortunately the installation does not work but ends with a kernel panic before things really get started:

![Screenshot 2021-07-28 141419](https://user-images.githubusercontent.com/7888607/127321458-22ceac5a-9dbc-4bd4-9d4d-768e3a331273.png)

**Comment by fansari** [comment]
When I run:
cpio -ivd < initrd

I get:
../proxmox.iso

**Comment by Exellent1988** [comment]
@fansari  try the forked version plz ( the one in the pull request: https://github.com/Exellent1988/pve-iso-2-pxe
the where some other errors in the scrypt by morph as well...

**Comment by fansari** [comment]
@Exellent1988 Thank you. With this forked version the Proxmox installer is starting.

**Comment by dagmoller** [comment]
> @fansari try the forked version plz ( the one in the pull request: https://github.com/Exellent1988/pve-iso-2-pxe
> the where some other errors in the scrypt by morph as well...

This fork works with Proxmox Backup Server 2.0 too... THX

**Comment by morph027** [comment]
Thanks @Exellent1988 for the hint regarding `x-zstd`. I've added this and fixed the extracting error too in https://github.com/morph027/pve-iso-2-pxe/commit/f32cc7f9e9d0b5be46752dfb5e8d1c4d963d5894
