### ISSUE TITLE
Can't eject proxmox

### ISSUE THREAD

**Issue by devinwangyu** [morph027/pve-iso-2-pxe#22]
I can install proxmox 6.4 using the script of the previous version; but I cannot install proxmox 7.0 using this script，this cannot pop up the installation interface；can you help me，thanks！

**Comment by devinwangyu** [comment]
I USE PXE (TFTP)

label proxmox-install
     menu label Install Proxmox
     linux proxmox/7.0-1/linux26
     append vga=791 video=vesafb:ywrap,mtrr ramdisk_size=1677216 rw quiet splash=silent
     initrd proxmox/7.0-1/initrd

**Comment by morph027** [comment]
Do you have any log output or a screenshot?

**Comment by devinwangyu** [comment]
Hi，morph027
Log on the server

Jul 21 21:35:02 node11 dhcpd: DHCPDISCOVER from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:03 node11 dhcpd: DHCPOFFER on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPREQUEST for 192.168.183.13 (192.168.183.211) from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPACK on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 xinetd[1722]: START: tftp pid=1740 from=192.168.183.13
Jul 21 21:35:04 node11 in.tftpd[1741]: Error code 0: TFTP Aborted
Jul 21 21:35:04 node11 in.tftpd[1742]: Client 192.168.183.13 finished pxelinux.0
Jul 21 21:35:04 node11 in.tftpd[1753]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1754]: Client 192.168.183.13 finished boot.msg
Jul 21 21:35:04 node11 in.tftpd[1756]: Client 192.168.183.13 finished vesamenu.c32
Jul 21 21:35:04 node11 in.tftpd[1757]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1758]: Client 192.168.183.13 finished splash.png
Jul 21 21:35:15 node11 in.tftpd[1759]: Client 192.168.183.13 finished proxmox/7.0-1/linux26
Jul 21 21:41:08 node11 in.tftpd[1760]: Client 192.168.183.13 finished proxmox/7.0-1/initrd
Jul 21 21:50:15 node11 xinetd[1722]: EXIT: tftp status=0 pid=1740 duration=911(sec)
===================================================
And the client is always a black screen，thanks!

**Comment by devinwangyu** [comment]
Hi，morph027
Log on the server

Jul 21 21:35:02 node11 dhcpd: DHCPDISCOVER from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:03 node11 dhcpd: DHCPOFFER on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPREQUEST for 192.168.183.13 (192.168.183.211) from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPACK on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 xinetd[1722]: START: tftp pid=1740 from=192.168.183.13
Jul 21 21:35:04 node11 in.tftpd[1741]: Error code 0: TFTP Aborted
Jul 21 21:35:04 node11 in.tftpd[1742]: Client 192.168.183.13 finished pxelinux.0
Jul 21 21:35:04 node11 in.tftpd[1753]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1754]: Client 192.168.183.13 finished boot.msg
Jul 21 21:35:04 node11 in.tftpd[1756]: Client 192.168.183.13 finished vesamenu.c32
Jul 21 21:35:04 node11 in.tftpd[1757]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1758]: Client 192.168.183.13 finished splash.png
Jul 21 21:35:15 node11 in.tftpd[1759]: Client 192.168.183.13 finished proxmox/7.0-1/linux26
Jul 21 21:41:08 node11 in.tftpd[1760]: Client 192.168.183.13 finished proxmox/7.0-1/initrd
Jul 21 21:50:15 node11 xinetd[1722]: EXIT: tftp status=0 pid=1740 duration=911(sec)
===================================================
And the client is always a black screen，thanks!

**Comment by devinwangyu** [comment]
Hi，morph027
Log on the server

Jul 21 21:35:02 node11 dhcpd: DHCPDISCOVER from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:03 node11 dhcpd: DHCPOFFER on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPREQUEST for 192.168.183.13 (192.168.183.211) from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPACK on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 xinetd[1722]: START: tftp pid=1740 from=192.168.183.13
Jul 21 21:35:04 node11 in.tftpd[1741]: Error code 0: TFTP Aborted
Jul 21 21:35:04 node11 in.tftpd[1742]: Client 192.168.183.13 finished pxelinux.0
Jul 21 21:35:04 node11 in.tftpd[1753]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1754]: Client 192.168.183.13 finished boot.msg
Jul 21 21:35:04 node11 in.tftpd[1756]: Client 192.168.183.13 finished vesamenu.c32
Jul 21 21:35:04 node11 in.tftpd[1757]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1758]: Client 192.168.183.13 finished splash.png
Jul 21 21:35:15 node11 in.tftpd[1759]: Client 192.168.183.13 finished proxmox/7.0-1/linux26
Jul 21 21:41:08 node11 in.tftpd[1760]: Client 192.168.183.13 finished proxmox/7.0-1/initrd
Jul 21 21:50:15 node11 xinetd[1722]: EXIT: tftp status=0 pid=1740 duration=911(sec)
===================================================
And the client is always a black screen，thanks!

**Comment by devinwangyu** [comment]
Hi，morph027
Log on the server

Jul 21 21:35:02 node11 dhcpd: DHCPDISCOVER from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:03 node11 dhcpd: DHCPOFFER on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPREQUEST for 192.168.183.13 (192.168.183.211) from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPACK on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 xinetd[1722]: START: tftp pid=1740 from=192.168.183.13
Jul 21 21:35:04 node11 in.tftpd[1741]: Error code 0: TFTP Aborted
Jul 21 21:35:04 node11 in.tftpd[1742]: Client 192.168.183.13 finished pxelinux.0
Jul 21 21:35:04 node11 in.tftpd[1753]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1754]: Client 192.168.183.13 finished boot.msg
Jul 21 21:35:04 node11 in.tftpd[1756]: Client 192.168.183.13 finished vesamenu.c32
Jul 21 21:35:04 node11 in.tftpd[1757]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1758]: Client 192.168.183.13 finished splash.png
Jul 21 21:35:15 node11 in.tftpd[1759]: Client 192.168.183.13 finished proxmox/7.0-1/linux26
Jul 21 21:41:08 node11 in.tftpd[1760]: Client 192.168.183.13 finished proxmox/7.0-1/initrd
Jul 21 21:50:15 node11 xinetd[1722]: EXIT: tftp status=0 pid=1740 duration=911(sec)
===================================================
And the client is always a black screen，thanks!

**Comment by devinwangyu** [comment]
Hi，morph027
Log on the server
Jul 21 21:35:02 node11 dhcpd: DHCPDISCOVER from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:03 node11 dhcpd: DHCPOFFER on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPREQUEST for 192.168.183.13 (192.168.183.211) from 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 dhcpd: DHCPACK on 192.168.183.13 to 00:0c:29:6b:3e:90 via ens33
Jul 21 21:35:04 node11 xinetd[1722]: START: tftp pid=1740 from=192.168.183.13
Jul 21 21:35:04 node11 in.tftpd[1741]: Error code 0: TFTP Aborted
Jul 21 21:35:04 node11 in.tftpd[1742]: Client 192.168.183.13 finished pxelinux.0
Jul 21 21:35:04 node11 in.tftpd[1753]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1754]: Client 192.168.183.13 finished boot.msg
Jul 21 21:35:04 node11 in.tftpd[1756]: Client 192.168.183.13 finished vesamenu.c32
Jul 21 21:35:04 node11 in.tftpd[1757]: Client 192.168.183.13 finished pxelinux.cfg/default
Jul 21 21:35:04 node11 in.tftpd[1758]: Client 192.168.183.13 finished splash.png
Jul 21 21:35:15 node11 in.tftpd[1759]: Client 192.168.183.13 finished proxmox/7.0-1/linux26
Jul 21 21:41:08 node11 in.tftpd[1760]: Client 192.168.183.13 finished proxmox/7.0-1/initrd
Jul 21 21:50:15 node11 xinetd[1722]: EXIT: tftp status=0 pid=1740 duration=911(sec)

And the client is always a black screen，thanks!

**Comment by Exellent1988** [comment]
Sounds like the kernel panic from https://github.com/morph027/pve-iso-2-pxe/issues/21 without debug output, if quiet splash=silent then you'll only have a black screen
