### ISSUE TITLE
Can not build in ubuntu 20.04 desktop

### ISSUE THREAD

**Issue by DotaCoco** [morph027/pve-iso-2-pxe#24]
My operating system is ubuntu 20.04 desktop 
bash pve-iso-2-pxe.sh  proxmox-ve_6.3-1.iso 
Out Error 
gzip: >img: No such file or directory
gzip: initrdimg: No such file or directory
I get Error when try proxmox-ve_7.0-1.iso ,too!
why?
Are there any operating system requirements?

**Comment by morph027** [comment]
Hm, i'm using 20.04 myself and it's working. Can you run `bash -x pve-iso-2-pxe.sh proxmox-ve_6.3-1.iso` for more debugging?

**Comment by morph027** [comment]
Your're probably missing the `zstd gzip genisoimage` packages ([README](https://github.com/morph027/pve-iso-2-pxe#preparation))

**Comment by DotaCoco** [comment]
I try bash -x pve-iso-2-pxe.sh proxmox-ve_6.3-1.iso .
The Error:
07070100428F86000041ED0000000000000000000000025FBE774800000000000000080000000100000000000000000000000600000000devfs07070100000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000B00000000TRAILER!!!gzip: >img: No such file or directory
gzip: initrdimg: No such file or directory
+ exit 4

of course，I have the zstd gzip genisoimage packages

zjc@zjc-VivoBook:~/每月技术分享/55$ zstd --version
 zstd command line interface 64-bits v1.4.4, by Yann Collet 

zjc@zjc-VivoBook:~/每月技术分享/55$ gzip --version
gzip 1.10
Copyright (C) 2018 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
Written by Jean-loup Gailly.

zjc@zjc-VivoBook:~/每月技术分享/55$ genisoimage --version
genisoimage 1.1.11 (Linux)

**Comment by morph027** [comment]
Can you try the latest commit please?
