### ISSUE TITLE
v7.1 Support: handle mimetype=octet-stream

### ISSUE THREAD

**Issue by Nevermore24** [morph027/pve-iso-2-pxe#28]
The initrd file for v7.1 no longer appears to be compressed:
`file --mime-type --brief /tmp/initrd.img
application/octet-stream`

We will need to handle this file type case in order to support v7.1

**Comment by morph027** [comment]
Hm...works on my machine ;)

![Screenshot from 2022-03-25 07-36-19](https://user-images.githubusercontent.com/600106/160067588-4885116f-1c3d-4a3c-b970-dfdc594ae769.png)

Which OS are you running? Which version of the `file` command are you using?

**Comment by Nevermore24** [comment]
Hi, thanks for looking into it. I'm running Centos 7.9.2009 which ships with file 5.11-37

**Comment by Nevermore24** [comment]
That what it was, everything worked fine once I switched to using file-5.41
