### ISSUE TITLE
proxmox 5.2 seems to lock mouse/keyboard

### ISSUE THREAD

**Issue by si458** [morph027/pve-iso-2-pxe#3]
for some strange reason, when im using the latest 5.2 iso,
it detected ipxe correctly,
shows menu correctly,
even starts the setup correctly,

but then the mouse and keyboard are locked, any dont work?

i cant seem to do ANYTHING on the server without having the unplug/plug power back in?

**Comment by morph027** [comment]
Hi. Will have a look at it..

**Comment by morph027** [comment]
Still happening with 5.3? Or on other machines?

**Comment by si458** [comment]
Hi
Sadly I moved away from proxmox so I have no idea if it’s working or not 
If I have time and a spare server I will try again and let you no :)
