### ISSUE TITLE
ERROR: could not insert 'isst_if_mbox_msr': Input/output error

### ISSUE THREAD

**Issue by desnij** [morph027/pve-iso-2-pxe#31]
Erstens, vielen Dank für dieses Projekt.

I ran the master branch on debian 11 and the Proxmon 7.4 iso. then boot a server with the output files.

 I assume this is really the proxmox `/init` script, but I thought I would post this here since this repo didn't work out of the box for me.

``` shell
boot comandline: initrd=initrd ramdisk_size=16777216 rw quiet splash=verbose proxdebug console=tty1 console=ttyS1,115200 BOOT_IMAGE=linux26 BOOTIF=01-ac-1f-6b-ca-41-38  
loading drivers:  ahci nvme wmi acpi_pad ipmi_si ipmi_ssif mac_hid ioatdma intel_pch_thermal xhci_pci i2c_i801 pcspkr intel_cstate rapl aesni_intel ghash_clmulni_intel crc32_pclmul crct10dif_pclmul kvm_intel intel_powerclamp x86_pkg_temp_thermal isst_if_mbox_msr intel_rapl_common
modprobe: ERROR: could not insert 'isst_if_mbox_msr': Input/output error
found proxmox ISO image inside initrd image
Debugging mode (type 'exit' or press CTRL-D to continue startup)
```

My next steps: I am going read the images `/ init` script (see if I see anything) and then mount the iso and create a cpio version to see if that helps

**Comment by morph027** [comment]
https://forum.proxmox.com/threads/huawei-2288h-installing-error-could-not-insert-isst_if_mbox_msr.70065/

**Comment by desnij** [comment]
thanks for the post... Interesting I will look into it further
 but as I assume you have surmised this isn't really useful in my case since I am not using usb keys (and I have no physical access to the server I am working on)...

So thanks, if I find anything obvious I will let you know.
