### ISSUE TITLE
Problem with adding the iso file to intird

### ISSUE THREAD

**Issue by Boss-man** [morph027/pve-iso-2-pxe#43]
I'm trying to run this script on my Synology NAS, which dont have CPIO.
And I get to here: 7z x "../proxmox.iso" >> initrd || exit 5

But that just extract the ISO file to where the initrd file is, so it's not added to the file.
So when I pxe boot, I just get an error that Proxmox installer is looking for proxmox.iso and then fails.

Can this be done in Windows ?

**Comment by morph027** [comment]
Looks like you're right and 7z only supports extracting from cpio archives.

You could just setup Ubuntu w/ WSL (via Windows Store) on you Windows and execute the steps which should work.
