### ISSUE TITLE
A problem about zstd.

### ISSUE THREAD

**Issue by KinChin1** [morph027/pve-iso-2-pxe#44]
Hi, I got a problem when I run the script.
`zstd: /tmp/initrd.img: unsupported format`
I can run this script on other PVE version, but not the  PVE8.1.
I don't know why now, Can you help me？

**Comment by morph027** [comment]
Which version of `xz` are you using? (`xz --version`)

Just tried with 8.1 ISO and it worked for me.

**Comment by KinChin1** [comment]
xz (XZ Utils) 5.2.5
liblzma 5.2.5
Thank you for your reply.

**Comment by morph027** [comment]
Sorry, was on the wrong track. I mean the version of zstandard `zstd --version`

**Comment by KinChin1** [comment]
zstd command line interface 64-bits v1.4.8, by Yann Collet

**Comment by morph027** [comment]
Hm, works for me too

```bash
# bash pve-iso-2-pxe.sh proxmox.iso 

#########################################################################################################
# Create PXE bootable Proxmox image including ISO                                                       #
#                                                                                                       #
# Author: mrballcb @ Proxmox Forum (06-12-2012)                                                         #
# Thread: http://forum.proxmox.com/threads/8484-Proxmox-installation-via-PXE-solution?p=55985#post55985 #
# Modified: morph027 @ Proxmox Forum (23-02-2015) to work with 3.4                                      #
#########################################################################################################

Using proxmox-ve_8.1-2.iso...
extracting kernel...
extracting initrd...
adding iso file ...
2519017 blocks
Finished! pxeboot files can be found in /tmp/tmp.e1WIFTVrHo. 
# zstd --version
*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
```

Can you post the output of `file /tmp/initrd.img` after the script fails?

**Comment by KinChin1** [comment]
I already known the reason of my issue.
I got a script about unattened pve, need add some .sh file to image. And I added them on Windows10, then I run your script on ubuntu...
It's a stupid mistake, i'm so sorry for wasting your time.



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 3, 2024 15:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [morph027/pve-iso-2-pxe] A problem about zstd. (Issue #44)




 
Hm, works for me too
 # bash pve-iso-2-pxe.sh proxmox.iso  ######################################################################################################### # Create PXE bootable Proxmox image including ISO                                                       # #                                                                                                       # # Author: mrballcb @ Proxmox Forum (06-12-2012)                                                         # # Thread: http://forum.proxmox.com/threads/8484-Proxmox-installation-via-PXE-solution?p=55985#post55985 # # Modified: morph027 @ Proxmox Forum (23-02-2015) to work with 3.4                                      # ######################################################################################################### Using proxmox-ve_8.1-2.iso... extracting kernel... extracting initrd... adding iso file ... 2519017 blocks Finished! pxeboot files can be found in /root.  ***@***.***:~# zstd --version *** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
 
Can you post the output of file /tmp/initrd.img after the script fails?

**Comment by morph027** [comment]
Glad it works. No problem, this might help other users in the future as well.
