### ISSUE TITLE
no device with valid ISO found

### ISSUE THREAD

**Issue by audiocrush** [morph027/pve-iso-2-pxe#46]
Hi there,

somehow I'm getting the error message in the title when testing in virtualbox.
Is this expected?

I'm using an autoinstall iso that I have created using proxmox-auto-install-assistant because I want the machines to pxeboot and then get their config via an answer file from a URL they receive via  DHCP option 250.

![Screenshot 2024-06-05 172021](https://github.com/morph027/pve-iso-2-pxe/assets/1686780/39d670ed-d8c6-4ef0-9c66-9c3b6d8c3c66)

**Comment by audiocrush** [comment]
I also just tested this with a plain Proxmox VE 8.2-1 ISO I downloaded directly from the proxmox website and I get the same results.

Just for completeness:

to get the automated install running I had to edit the boot menu entry and add proxmox-start-auto-installer so it looks like this:
append vga=791 video=vesafb:ywrap,mtrr ramdisk_size=16777216 rw quiet splash=silent proxmox-start-auto-installer
instead of the way it is written in the manual like this:
append vga=791 video=vesafb:ywrap,mtrr ramdisk_size=16777216 rw quiet splash=silent

**Comment by morph027** [comment]
Probably too less memory?

`Initramfs unpacking failed: write error`

**Comment by audiocrush** [comment]
Oh!
you're right. apparently 4gb was not enough in my test-vm works with 8
thank you! :)

I did not expect this but in hindsight it makes sense, since mdmdisk loads the full initrd into memory and then unpacks it again to obtain the iso... so it makes sense and would probably never happen on a real server :D
