### ISSUE TITLE
Preseed?

### ISSUE THREAD

**Issue by NuxRo** [morph027/pve-iso-2-pxe#7]
Hi,

Quick question re the PXE installation. Have you managed to feed it a preseed file for a proper automatic installation? I wonder how much that is achievable, especially in getting all the right bits working properly (ZFS, bridges etc).

**Comment by morph027** [comment]
Hi!

Nah, the only way would be by preseeding a default debian and then add pve like in the wiki: https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Stretch (e.g. in preseed's late command)

**Comment by NuxRo** [comment]
Yes, thanks for confirming, that's what I am doing now, but that makes ZFS complicated.

**Comment by mihai-satmarean** [comment]
> Yes, thanks for confirming, that's what I am doing now, but that makes ZFS complicated.

Hi, we are trying the same, have you some code we could inspire from?
